Task 1656: Fix Locator icon animation
jdi-testing/jdn-ai pull request #1666
Opened 2024-03-05 11:01 UTC by KateDronova

![photo_2024-03-05_14-31-44](https://github.com/jdi-testing/jdn-ai/assets/98758686/d9f2ba76-a10a-4b1d-8e91-8b14e27a2c9e)
![photo_2024-03-05_14-32-30](https://github.com/jdi-testing/jdn-ai/assets/98758686/28a932e1-08e8-4ef2-91a8-36b506d6ec63)

2024-03-05 11:12 UTC, Iogsotot requested changes
Неплохо, но стоит порефакторить именование классов и распределение стилей по ним

2024-03-05 11:12 UTC, Iogsotot commented on src/features/locators/styles/locatorMenu.less
> +	&.jdn__itemsList-button.jdn__locator-list_button-menu {
мне кажется, тут стоить всё-таки переработать название классов так, чтобы префикс jdn__ использовался только один раз и не происходило задублирование
`.jdn__locator-list {
	text-align: left;
	&_button-menu {`
	
Что-то в эту сторону. Т.е. выделить общие сущности по БЭМу и разделить стили по ним

2024-03-07 07:19 UTC, KateDronova commented on src/features/locators/styles/locatorMenu.less
> +	&.jdn__itemsList-button.jdn__locator-list_button-menu {
Fixed that

2024-03-07 08:33 UTC, Iogsotot approved these changes

2024-03-07 08:33 UTC, Iogsotot commented on src/features/locators/Locator.tsx
> +                        className="jdn__itemsList-button jdn__itemsList-button_menu"
именование jdn__block_element--modificator
locator-list  -- имя одного element/block

2024-03-07 08:33 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
> +              className="jdn__itemsList-button jdn__itemsList-button_menu"
```suggestion
              className="jdn__itemsList-button jdn__items-list_button-menu"
```

2024-03-07 10:07 UTC, KateDronova commented on src/features/locators/components/LocatorListHeader.tsx
> +              className="jdn__itemsList-button jdn__itemsList-button_menu"
Done!

2024-03-07 10:08 UTC, KateDronova commented on src/features/locators/Locator.tsx
> +                        className="jdn__itemsList-button jdn__itemsList-button_menu"
Got it!

2024-03-07 11:06 UTC, merged