issue_1651 progress bar error state
jdi-testing/jdn-ai pull request #1673
Opened 2024-03-10 22:02 UTC by bklimov-web

2024-03-19 11:49 UTC, Iogsotot requested changes
https://github.com/jdi-testing/jdn-ai/assets/50149163/add31394-275b-4df6-a501-cb271a17f808
Возможно, баг связан с этим ПР, надо проверить.

По самой задаче - в проекте есть готовое решение аналогичного поведения для ProgressBar - `LocatorProgres.tsx`, возможно, стоит взять лоику оттуда и адаптировать для обработки ошибок в `ProgressBar.tsx`

2024-03-19 11:49 UTC, Iogsotot commented on src/features/pageObjects/styles/progressBar.less
> -		&.success {
именование `success` было дано для единнобразия с апи АнтД для прогресс бара, не совсем понимаю, зачем его переименовывать на `finished`

2024-03-19 11:49 UTC, Iogsotot commented on src/pageServices/pageDataHandlers.ts
> +export const setParents = async (elements: any) => {
```suggestion
export const setParents = async (elements: ILocator[]) => {
```

2024-03-19 11:49 UTC, Iogsotot commented on src/pageServices/pageDataHandlers.ts
> +};
это мне нравится - логика в одном месте, а не по разным файлам раскидана :+1:

2024-03-20 07:35 UTC, bklimov-web commented on src/pageServices/pageDataHandlers.ts
> +export const setParents = async (elements: any) => {
Спасибо, не углядел)

2024-03-20 07:47 UTC, bklimov-web commented on src/features/pageObjects/progressBar.slice.ts
> +      state.error = action.payload || '';
Согласен, исправлю

2024-03-20 08:37 UTC, bklimov-web commented on src/features/pageObjects/styles/progressBar.less
> -		&.success {
Потому что тут ширина блока зависит от наличия круглешка со статусом. Он раньше был только при success статусе, а теперь еще и на ошибке выдается. Поэтому пришлось как-то обобщить название. Большого смысла связывать это название с апи antd я не вижу, честно говоря, это ж просто название класса)

2024-03-25 07:09 UTC, Iogsotot commented on src/features/pageObjects/styles/progressBar.less
> -      transition: width linear 100ms;
почему понадобилось убирать transition?

2024-03-25 08:08 UTC, Iogsotot approved these changes

2024-03-26 14:08 UTC, Iogsotot approved these changes
Спасибо за работу, выглядит очень хорошо!

2024-03-26 18:03 UTC, merged