Task 1661: Fix Disable right click locator selection
jdi-testing/jdn-ai pull request #1681
Opened 2024-03-17 08:13 UTC by KateDronova

![Screenshot_2](https://github.com/jdi-testing/jdn-ai/assets/98758686/acc66597-fecf-4607-b3bb-df6b9fc18b2b)

2024-03-18 12:11 UTC, Iogsotot requested changes

2024-03-18 12:11 UTC, Iogsotot commented on src/pageServices/contentScripts/selectable.js
> -            toggleActiveClass(highlightTarget);
потерялся функционал: при клике ПКМ на неактивный элемент он становится активным и открывается меню
было: ![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/ccc2d716-ff6a-4a69-9fb0-88c5d62335a7)

теперь:
не работает + ошибка в консоли контент-скриптов
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/8308efb7-48a7-4d68-ac37-43316ea38de4)

2024-03-18 12:14 UTC, KateDronova commented on src/pageServices/contentScripts/selectable.js
> -            toggleActiveClass(highlightTarget);
Я этот функционал и убрала - в этом и была задача ведь: разделить функционалы ЛКМ и ПКМ - нет?

2024-03-18 12:38 UTC, Iogsotot commented on src/pageServices/contentScripts/selectable.js
> -            toggleActiveClass(highlightTarget);
да, ты права, спасибо, что указала. Тогда только ошибку из консоли убрать на клик и всё ок

2024-03-29 08:34 UTC, closed without merging

2024-03-29 08:34 UTC, KateDronova commented
См. https://github.com/jdi-testing/jdn-ai/pull/1694