Issue 1534 disabling collapse element new
jdi-testing/jdn-ai pull request #1691
Opened 2024-03-28 11:40 UTC by Alinochka07

2024-03-29 09:23 UTC, Iogsotot requested changes
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/05d0f878-bf37-4476-952d-f546523a7a59)
Если нет PageObject вообще (пустой лист PO), то CaretDown тоже должен быть disabled

2024-03-29 09:23 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
> +            }}
логику лучше обернуть в функцию и в onClick передавать callback

2024-03-29 09:23 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
>              }}
было бы здорово, если бы ты перенесла inline стили в файл со стилями

2024-03-29 09:53 UTC, Iogsotot commented
В целом всё ок, нужны небольшие правки

я бы рекомендовала создать два состояния для каретки - isDisabled: true и isDisabled: false
isDisabled должно быть комплексным состоянием: стрелка повёрнута вниз, цвет цвет 000000 25% (Character/Disabled); это состояние наступает, когда нет PO, когда нет древовидной структуры локаторов

Ещё заметила какое-то дёрганье каретки, возможно это связано с useEffect и логикой внутри него
https://github.com/jdi-testing/jdn-ai/assets/50149163/076dc8d2-f67d-4ff1-ae3f-f8db3e16ad30

2024-03-29 09:57 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
> +              pointerEvents: isDisabled || !hasSubLocators ? 'none' : 'auto',
почему ты использовала pointerEvents тут, а не cursor?

2024-04-05 10:05 UTC, Alinochka07 commented on src/features/locators/components/LocatorListHeader.tsx
> +              pointerEvents: isDisabled || !hasSubLocators ? 'none' : 'auto',
исправила на cursor.

2024-04-05 10:06 UTC, Alinochka07 commented on src/features/locators/components/LocatorListHeader.tsx
> +            color={`${isDisabled || !hasSubLocators ? 'rgba(0, 0, 0, 0.25)' : '#878A9C'}`}
исправлено

2024-04-05 10:07 UTC, Alinochka07 commented on src/features/locators/components/LocatorListHeader.tsx
> +            }}
ок. обернула в функцию.

2024-04-05 10:07 UTC, Alinochka07 commented on src/features/locators/components/LocatorListHeader.tsx
>              }}
создала новый файл .less для каретки

2024-04-08 05:56 UTC, Alinochka07 commented
Насчет дерганья каретки, обернула логику в useCallback. Вроде у меня нормально показывает.
И переделано в целом все как и было запрошено в комментах.

2024-04-09 10:45 UTC, Iogsotot requested changes
Судя по коду и задаче, `header-collapse` может иметь 3 состояния:
disabled - быть НЕкликабельным, смотреть вниз, цвет 000000 25% (Character/Disabled)
expanded - стрелка вверх, кликабельный, активный цвет
collapsed - стрелка вниз, кликабельный, активный цвет

Как можно упростить и организовать эти стили?
К примеру так:

- выделить общее: "кликабельный" (курсор, евенты), активный цвет,  - вынести эти стили в общий класс `header-collapse`
- Затем можно вынести начальное (default) состояние для  `header-collapse` - это состояние можно обозначить классом, а можно оставить "по умолчанию". 
         - Если обозначить классом, то собрать все стили, отвечающие за default state в один класс (collapsed, как у тебя было сделано). 
         - Можно не обозначать отдельным классом, и тогда все стили, относящиеся к default state, перенести в `header-collapse`

- собрать все стили для `disabled` в одноименный класс (уже сделано, тут ок)
- написать логику, по которой собирается класс для `header-collapse` (используя [classnames](https://www.npmjs.com/package/classnames), например)
- отслеживать факторы, которые влияют на стейт коллапса и менять их по useEffect, props, useState или useMemo (выбрать наиболее оптимальный в данном кейсе вариант)

2024-04-09 10:45 UTC, Iogsotot commented on src/features/locators/styles/caretDown.less
CaretDown - это общий переиспользуемый компонент, логичнее держать его стили в src/common/styles/headerCollapse.less (туда же отправить все стили, относящиеся к caretDown - `header-collapse`)

2024-04-09 10:45 UTC, Iogsotot commented on src/features/pageObjects/styles/caretDownExpand.less
тут забыла почистить комментарии

молодец, что вынесла стили из компонента, осталось переместить их в один общий файл (см выше комент на src/features/locators/styles/caretDown.less )

2024-04-09 10:45 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
> +            } ${expandAll === ExpandState.Expanded && hasSubLocators ? 'expanded' : ''}`}
вычисление имя класса прямо в JSX ухудшает читабельность (важно), может повлиять на производительность (в данном случае минорно), может привести в ошибкам, тк в таком виде их тяжелее поддерживать (важно)

2024-04-09 10:45 UTC, Iogsotot commented on src/features/locators/styles/caretDown.less
> +    &.has-sub-locators {
классы в стилях обычно не должны описывать логику, происходящую в скриптах. Они отражают состояние, поведение, внешний вид

https://ru.hexlet.io/blog/posts/oshibki-imenovaniya-v-vyorstke
https://github.com/yoksel/common-words

2024-04-10 09:13 UTC, Iogsotot commented on src/features/locators/components/LocatorListHeader.tsx
> +  }, [updateLocatorsInfo]);
код выглядит переусложнённым, мне кажется тут лучше поправить логику - понять, почему приходят неактуальные данные (для чего ты используешь мемоизацию) и/или заменить связку useEffect + useCallback на useMemo

2024-04-11 09:28 UTC, Alinochka07 commented on src/features/locators/styles/caretDown.less
сделано

2024-05-29 12:19 UTC, closed without merging