Issue 1588: Escaping linkText locator value
jdi-testing/jdn-ai pull request #1697
Opened 2024-04-01 12:39 UTC by TossACoinToUrProgrammer

- https://github.com/jdi-testing/jdn-ai/issues/1588

Before: 
![1before](https://github.com/jdi-testing/jdn-ai/assets/59771669/b7028c4e-9fe7-4fb1-8cef-c416b092c472)
![3before](https://github.com/jdi-testing/jdn-ai/assets/59771669/14126698-5752-49d2-b6a1-54567cbf39ea)

After:
![1after](https://github.com/jdi-testing/jdn-ai/assets/59771669/bed16a65-5939-4820-9edb-de210cf55f4a)
![3after](https://github.com/jdi-testing/jdn-ai/assets/59771669/057ea875-989a-4470-b878-ba08e99e26a7)

2024-04-01 13:40 UTC, KateDronova reviewed
Seems to work as indended 👍 (only rise the version)

2024-04-01 13:50 UTC, Iogsotot commented
Мне кажется, вывод в text area не надо было менять

Экранирование символов должно происходить на копирование в буффер обмена:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/ea432ee1-d364-4849-96bd-641fe44e2f6e)
и в результирующем java файле  (есть на скринах)

2024-04-01 13:56 UTC, Iogsotot requested changes

2024-04-01 13:56 UTC, Iogsotot commented on src/features/pageObjects/utils/pageObjectTemplate.ts
> +    let locatorEscaped = escapeString(unescapeString(locator.locatorValue.output)) //unescape first in case the locator has already been escaped
если переменная не переназначается, то лучше использовать const

2024-04-01 13:56 UTC, Iogsotot commented on src/features/pageObjects/utils/pageObjectTemplate.ts
> +    let locatorEscaped = escapeString(unescapeString(locator.locatorValue.output)) //unescape first in case the locator has already been escaped
как может произойти ситуация, что к нам в locatorsCode попадает локатор, который был заранее экранирован?
Возможно, будет правильнее найти место экранирования и изменить логику под ту, что нам нужна сейчас? (вместо " escapeString(unescapeString) "

2024-04-02 10:39 UTC, TossACoinToUrProgrammer commented on src/features/pageObjects/utils/pageObjectTemplate.ts
> +    let locatorEscaped = escapeString(unescapeString(locator.locatorValue.output)) //unescape first in case the locator has already been escaped
т.к. у меня экранированные символы можно увидеть в textarea, и удалить их, то escapeString(unescapeString) было бы слоем защиты, чтобы в download не попали неэкранированные символы. Но да, сейчас буду делать textarea без экр, и этот участок кода исправлять

2024-05-07 07:42 UTC, closed without merging