Issue 739 tooltip align fix
jdi-testing/jdn-ai pull request #1723
Opened 2024-04-19 08:46 UTC by Alinochka07

[Ссылка на задачу](https://github.com/jdi-testing/jdn-ai/issues/739)

Расстояние между стрелкой тултипа и иконкой стало теперь одного размера для всех случаев.
Исчез стык между стрелкой и телом тултипа в суб-локаторе, где была кнопка копирования.

Новая ветка на задачу.

2024-04-19 08:53 UTC, Alinochka07 commented
Создана новая ветка. Предыдущая: `issue_739-tooltip-align-fix-seam` будет удалена и ПР `https://github.com/jdi-testing/jdn-ai/pull/1717` тоже будет закрыт.

2024-04-24 11:09 UTC, Iogsotot commented
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/24aad454-de64-476d-bec1-1ba9f0370845)
этот комит мне очень сильно не нравится.
Как будет готов ПР - напиши в нашем чатике в дискорде, пожалуйста

2024-04-24 11:36 UTC, Iogsotot requested changes
надо поправить историю комитов:

- внутри ПР должен быть актуальный мастер
- комиты должны содержать только твои изменения
- не должно быть слишком длинной и запутанной истории комитов

2024-04-24 11:36 UTC, Iogsotot commented on manifest.json
> +  "host_permissions": ["http://*/*", "https://*/*", "file://*"],
надо вернуть форматирование как было

2024-04-24 11:36 UTC, Iogsotot commented on src/features/pageObjects/components/PageObjGenerationSettings.tsx
> +            value={isCurrentFrameworkVividus ? 'Not applicable' : currentAnnotation}
выглядит как код из мастера, но почему-то он заново пишет под твоим авторством

2024-04-24 11:36 UTC, Iogsotot commented on src/features/pageObjects/components/PageObjSettingsItem.tsx
> +
код из мастера, он не должен заново добавляться

2024-04-24 11:36 UTC, Iogsotot commented on src/features/pageObjects/components/PageObjSettingsItem.tsx
> +        )}
код из мастера

2024-04-24 13:48 UTC, Iogsotot commented
попробуй git reset до начала ветки и заново собрать комиты
(не забудь скопировать ветку до начала манипуляций)

2024-05-03 09:47 UTC, Alinochka07 commented on src/features/pageObjects/components/PageObjGenerationSettings.tsx
> +            value={isCurrentFrameworkVividus ? 'Not applicable' : currentAnnotation}
эти файлы были исключены из ПР

2024-05-03 09:47 UTC, Alinochka07 commented on src/features/pageObjects/components/PageObjSettingsItem.tsx
> +
Тоже был исключен

2024-05-03 09:49 UTC, Alinochka07 commented on src/features/pageObjects/components/PageObjSettingsItem.tsx
> +        )}
здесь были все же внесены изменения, чтобы было единое позиционирование тултипа.

2024-05-07 07:37 UTC, Iogsotot commented
Всё готово к мерджу.

Что сделала, чтобы поправить историю комитов: 
0. (обновила мастер по последнему origin)
1. сбросила историю комитов git reset **--soft**
2. нашла твой код, добавила проиндексировала, добавила в комит [fix: align tooltips, seams](https://github.com/jdi-testing/jdn-ai/pull/1723/commits/c0d69ad216631327c4d61cd73d7b94e7b8e594a9)
3. ребейзнула ветку по локальному (и обновленному) мастеру
4. подняла версию плагина npm run patch 
5. запушила все изменения через --force на origin

2024-05-07 07:37 UTC, Iogsotot approved these changes

2024-05-07 07:46 UTC, merged